/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesNewRouteImport } from './routes/recipes/new'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes/$recipeId'
import { Route as TabsWeekRouteImport } from './routes/_tabs/week'
import { Route as TabsRecipesIndexRouteImport } from './routes/_tabs/recipes/index'
import { Route as RecipesRecipeIdEditRouteImport } from './routes/recipes/$recipeId_.edit'

const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsWeekRoute = TabsWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => TabsRoute,
} as any)
const TabsRecipesIndexRoute = TabsRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => TabsRoute,
} as any)
const RecipesRecipeIdEditRoute = RecipesRecipeIdEditRouteImport.update({
  id: '/recipes/$recipeId_/edit',
  path: '/recipes/$recipeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/week': typeof TabsWeekRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/recipes/': typeof TabsRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/week': typeof TabsWeekRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/recipes': typeof TabsRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/_tabs/week': typeof TabsWeekRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/$recipeId_/edit': typeof RecipesRecipeIdEditRoute
  '/_tabs/recipes/': typeof TabsRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/week'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/recipes/$recipeId/edit'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/week'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/recipes/$recipeId/edit'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/_tabs/week'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/recipes/$recipeId_/edit'
    | '/_tabs/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
  RecipesNewRoute: typeof RecipesNewRoute
  RecipesRecipeIdEditRoute: typeof RecipesRecipeIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/week': {
      id: '/_tabs/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof TabsWeekRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/recipes/': {
      id: '/_tabs/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof TabsRecipesIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/recipes/$recipeId_/edit': {
      id: '/recipes/$recipeId_/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof RecipesRecipeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TabsRouteChildren {
  TabsWeekRoute: typeof TabsWeekRoute
  TabsRecipesIndexRoute: typeof TabsRecipesIndexRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsWeekRoute: TabsWeekRoute,
  TabsRecipesIndexRoute: TabsRecipesIndexRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
  RecipesNewRoute: RecipesNewRoute,
  RecipesRecipeIdEditRoute: RecipesRecipeIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
